#' Train a fast surrogate emulator of the flood model
#'
#' Builds a machine-learning emulator that approximates the routing model's
#' depth response to its parameters, so that many what-if scenarios can be
#' explored far faster than re-running the full pipeline. Training data are
#' generated by evaluating the Manning depth relation across sampled parameters;
#' the surrogate then predicts depth for new parameter sets.
#'
#' When \pkg{ranger} is installed, a random forest is used; otherwise a
#' log-linear model provides a dependency-free fallback (exact for the
#' power-law Manning relation, and a reasonable approximation more generally).
#' The surrogate is a convenience for rapid exploration and interpolation, not a
#' replacement for the physical model.
#'
#' @param x A \code{flood_project} whose \code{route} slot supplies the fixed
#'   slope and discharge context, or a \code{flood_route} object directly.
#' @param n_train Number of training samples. Default \code{500}.
#' @param n_range,width_range Length-2 priors for Manning's \eqn{n} and channel
#'   width used to generate training data.
#' @param seed Optional integer seed for reproducibility.
#'
#' @return If \code{x} is a \code{flood_project}, the same object with its
#'   \code{surrogate} entry stored in \code{meta} (the project schema has no
#'   dedicated slot) and the stage logged. Otherwise a list of class
#'   \code{flood_surrogate} with elements \code{engine} (\code{"ranger"} or
#'   \code{"loglinear"}), \code{predict} (a function taking a data frame with
#'   columns \code{Q}, \code{n}, \code{width} and returning predicted depth),
#'   \code{performance} (in-sample \code{rmse} and \code{r2}), and
#'   \code{settings}.
#'
#' @examples
#' disc <- data.frame(
#'   date = seq(as.Date("2020-06-01"), by = "day", length.out = 12),
#'   Q_mm = c(0, 1, 3, 8, 18, 30, 22, 14, 8, 4, 2, 1)
#' )
#' r <- flood_route(disc, area_km2 = 300)
#' s <- flood_surrogate(r, n_train = 300, seed = 1)
#' s$performance
#' # Predict depth for new parameter sets, fast
#' s$predict(data.frame(Q = 150, n = 0.04, width = 25))
#'
#' @seealso \code{\link{flood_route}} for the model being emulated.
#' @export
flood_surrogate <- function(x, n_train = 500,
                            n_range = c(0.02, 0.08),
                            width_range = c(10, 40),
                            seed = NULL) {
  is_project <- is_flood_project(x)
  route <- if (is_project) x$route else x

  if (is.null(route) || !inherits(route, "flood_route")) {
    stop("No routing result found. Run flood_route() first.", call. = FALSE)
  }
  if (!is.null(seed)) set.seed(seed)

  slope <- route$settings$slope
  peak_Q <- max(route$routed$Q_routed)

  # Generate training data spanning the parameter space and a discharge range
  Q <- stats::runif(n_train, 0.3 * peak_Q + 1e-6, 1.5 * peak_Q + 1)
  n <- stats::runif(n_train, n_range[1], n_range[2])
  width <- stats::runif(n_train, width_range[1], width_range[2])
  depth <- manning_depth(Q, n, width, slope)
  train <- data.frame(Q = Q, n = n, width = width, depth = depth)

  if (has_engine("ranger")) {
    fit <- ranger::ranger(depth ~ Q + n + width, data = train,
                          num.trees = 200)
    predict_fn <- function(newdata) {
      stats::predict(fit, data = newdata)$predictions
    }
    engine <- "ranger"
  } else {
    # Log-linear fallback (exact for the Manning power law)
    fit <- stats::lm(log(depth) ~ log(Q) + log(n) + log(width), data = train)
    predict_fn <- function(newdata) {
      exp(stats::predict(fit, newdata = data.frame(
        Q = newdata$Q, n = newdata$n, width = newdata$width)))
    }
    engine <- "loglinear"
  }

  # In-sample performance
  pred <- predict_fn(train)
  rmse <- sqrt(mean((pred - train$depth)^2))
  ss_res <- sum((pred - train$depth)^2)
  ss_tot <- sum((train$depth - mean(train$depth))^2)
  r2 <- if (ss_tot > 0) 1 - ss_res / ss_tot else NA_real_

  result <- structure(
    list(engine = engine,
         predict = predict_fn,
         performance = c(rmse = round(rmse, 5), r2 = round(r2, 5)),
         settings = list(slope = slope, n_train = n_train,
                         n_range = n_range, width_range = width_range)),
    class = "flood_surrogate"
  )

  if (is_project) {
    x$meta$surrogate <- result
    x <- log_stage(x, "surrogate")
    return(x)
  }
  result
}

#' Print a flood surrogate
#'
#' @param x A \code{flood_surrogate} object.
#' @param ... Ignored, present for S3 method consistency.
#' @return The object \code{x}, invisibly; prints a compact summary.
#' @examples
#' disc <- data.frame(date = seq(as.Date("2020-06-01"), by = "day",
#'                                length.out = 12),
#'                    Q_mm = c(0, 1, 3, 8, 18, 30, 22, 14, 8, 4, 2, 1))
#' print(flood_surrogate(flood_route(disc, area_km2 = 300),
#'                       n_train = 200, seed = 1))
#' @export
print.flood_surrogate <- function(x, ...) {
  cat("<flood_surrogate>\n")
  cat("  engine: ", x$engine, "\n", sep = "")
  cat(sprintf("  training samples: %d\n", x$settings$n_train))
  cat(sprintf("  in-sample fit: RMSE=%.4f  R2=%.4f\n",
              x$performance[["rmse"]], x$performance[["r2"]]))
  cat("  use $predict(data.frame(Q=, n=, width=)) for fast depth estimates\n")
  invisible(x)
}
